server:
  port: 8088
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssvms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # MQTT
  mqtt:
    # 服务器连接地址，如果有多个，用逗号隔开
    host: tcp://127.0.0.1:1883
    # 连接服务器默认客户端ID
    clientId: java001
    # 默认的消息推送主题，实际可在调用接口时指定
    topic: publishAttribute,operation
    # 用户名
    username: admin
    # 密码
    password: admin
    # 连接超时
    timeout: 30
    # 心跳
    keepalive: 60


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ysu.domain
